import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/providers/theme-provider'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

// Find a way to change them with props or imported values
export const metadata: Metadata = {
  title: 'Mike Odnis',
  description: 'Generated by create next app',
  metadataBase: new URL('')
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>

      </Head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
